### ISSUE TITLE
Hello I still have the same problem   I do not understand

### ISSUE THREAD

**Issue by turpez** [duc010298-1/translate-renpy#5]
Total dialogue done on thread 1: 0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\micka\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\micka\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "trans-ren.py", line 411, in runner
    input_text_area = driver.find_element(By.XPATH, XPATH_INPUT)
  File "C:\Users\micka\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\micka\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\micka\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div[1]/div[2]/div[2]/c-wiz[1]/span/span/div/textarea"}
  (Session info: chrome=90.0.4430.93)

Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div[1]/div[2]/div[2]/c-wiz[1]/span/span/div/textarea"}           Problem line

**Comment by duc010298-1** [comment]
Do you run the tool with the `--show-browser` flag? Does the chrome browser automatically open the GG Translate page?

**Comment by turpez** [comment]
found cookie problem
